baseURL = "https://guilbert-alize.github.io/cv.alize.io/"
environment = "production"
languageCode = "fr"
title = "CV Alizé GUILBERT"
theme = "toha"
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true
enableEmoji = true
disableSearch = false

# Allow raw html in markdown file
[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    baseURL = "https://guilbert-alize.github.io/cv.alize.io/en/"

  [languages.fr]
    languageName = "Français"
    weight = 2
    baseURL = "https://guilbert-alize.github.io/cv.alize.io/fr/"

[params]
  background = "/images/site/background.jpg"
  [params.logo]
    main = "/images/site/favicon.png"
    inverted = "/images/site/favicon.png"
    favicon = "/images/site/favicon.png"

  gitRepo = "https://github.com/cv.alize.io"
  gitBranch = "main"

  [params.topNavbar]
    maxVisibleSections = 5

  [params.features]
    [params.features.darkMode]
      enable = false
      [params.features.darkMode.services.darkreader]
        defaultColorScheme = "system"
        fixes = { invert = ["img[src$=\".svg\"]"] }
        [params.features.darkMode.services.darkreader.theme]
          brightness = 100
          contrast = 100
          sepia = 0

    [params.features.portfolio]
      enable = false

    [params.features.blog]
      enable = false
      [params.features.blog.shareButtons]
        facebook = false
        twitter = true
        linkedin = true
        reddit = true
        whatsapp = false
        email = true
        mastodon = true

    [params.features.notes]
      enable = false

    [params.features.comment]
      enable = false
      [params.features.comment.disqus]
        shortName = "toha-example-site"

    [params.features.analytics]
      enabled = true
      [params.features.analytics.services.matomo]
        instance = "stats.mousqueton.io"
        siteId = 12

  enableTOC = false
  enableTags = false

  [params.footer]
    enable = false
    template = "footer.html"

    [params.footer.navigation]
      enable = true

    [params.footer.contactMe]
      enable = true

    [params.footer.credentials]
      enable = false

    [params.footer.newsletter]
      enable = false
      provider = "mailchimp"
      mailchimpURL = ""

    [params.footer.disclaimer]
      enable = false
