baseURL: "https://guilbert-alize.github.io/cv.alize.io/"
languageCode: en-us
title: "CV Alizé GUILBERT"
theme: toha

languages:
  en:
    languageName: English
    weight: 1
    contentDir: content/en
    params:
      url: /en/
  fr:
    languageName: Français
    weight: 2
    contentDir: content/fr
    params:
      url: /fr/

# Ensure all languages are in subdirectories
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# Allow raw HTML in markdown files
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Required outputs for HTML content and client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

params:
  background: "/images/site/background.jpg"
  darkBackground: "/images/site/darkbackground.jpg"
  logo:
    main: "/images/site/favicon.png"
    inverted: "/images/site/favicon.png"
    favicon: "/images/site/favicon.png"
  gitRepo: "https://github.com/cv.alize.io"
  gitBranch: "main"
  topNavbar:
    maxVisibleSections: 9
  features:
    darkMode:
      enable: true
      services:
        darkreader:
          defaultColorScheme: "system"
          fixes:
            invert:
              - "img[src$=\".svg\"]"
          theme:
            brightness: 100
            contrast: 100
            sepia: 0
    portfolio:
      enable: false
    blog:
      enable: false
      shareButtons:
        facebook: false
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: false
        email: true
        mastodon: true
    notes:
      enable: false
    comment:
      enable: false
      disqus:
        shortName: "toha-example-site"
    analytics:
      enabled: false
      services:
        matomo:
          instance: ""
          siteId: 12
  enableTOC: false
  enableTags: false
  footer:
    enable: false
    template: "footer.html"
    navigation:
      enable: true
    contactMe:
      enable: true
    credentials:
      enable: false
    newsletter:
      enable: false
      provider: "mailchimp"
      mailchimpURL: ""
    disclaimer:
      enable: false
