baseURL = 'https://cv.alize/io/'
languageCode = 'en-us'
title = 'CV Alizé GUILBERT'
theme = 'toha'
defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1
