name: github pages

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify --enableGitInfo --baseURL "https://guilbert-alize.github.io/cv.alize.io/" --environment production --disableKinds=sitemap,taxonomy,term

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          # Utilise ce token si tu veux utiliser le token GitHub Actions par défaut
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Ou utilise un PAT que tu auras créé et ajouté en secret sous PAT_TOKEN
          # token: ${{ secrets.PAT_TOKEN }}

          publish_dir: ./public
          publish_branch: gh-pages
